### ISSUE TITLE
class constants page not found

### ISSUE THREAD

**Issue by avikdal** [learn-co-curriculum/phase-3-quiz-class-variables-and-methods#2]
### Canvas Link

https://learning.flatironschool.com/courses/5843/quizzes/39504

### Concern

In reviewing the quiz for class variables and methods, there is a link to sources about class constants, and both of those links take me to a "page not found."

**Comment by lizbur10** [comment]
Hi @avikdal ! Thanks for bringing this to our attention - the broken links have now been fixed. 💙
