### ISSUE TITLE
Question 6 on Class Variables and Methods Example was supposed to be a Class Method, but was not

### ISSUE THREAD

**Issue by ckelly38** [learn-co-curriculum/phase-3-quiz-class-variables-and-methods#3]
### Canvas Link

https://learning.flatironschool.com/courses/6559/quizzes/47505

### Concern

Question 6
1 / 1 pts
Consider the following code:

class Book:

  genres = []

  def __init__(self, title, author = "", page_count = 0):
    self.title = title
    self.author = author
    self.page_count = page_count

  def genre(self, genre):
    return GENRE
    

Every time a genre is added to a Book object, we want to store that genre in the class variable named genres. The code above doesn't currently do this. Select the code snippet that does.

  
1. class Book:

  genres = []

  def __init__(self, title, author = "", page_count = 0):
    self.title = title
    self.author = author
    self.page_count = page_count

  def genre(cls, genre):
    return cls.genres.append(genre)

Wow! Nailed it!! By calling cls.genres.append adding the genre to genres, we achieve exactly what we want.
  
2. class Book:

  genres = []

  def __init__(self, title, author = "", page_count = 0):
    self.title = title
    self.author = author
    self.page_count = page_count

def genre(cls, genre):
    return genres.append(genre)
3.  I don't know.

The only problem is that you need @classmethod just above the method; otherwise cls is just a normal parameter.

### Suggested Changes

The only problem is that you need @classmethod just above the method; otherwise cls is just a normal parameter. So add @classmethod above each of the definitions for the genre method.

**Comment by lizbur10** [comment]
Hi @ckelly38 - I've transferred this issue [here](https://github.com/learn-co-curriculum/python-p3-quiz-class-attributes-and-class-methods/issues/1). Thanks for posting it! 💙
